### ISSUE TITLE
New files need to be recognized

### ISSUE THREAD

**Issue by resTive2k12** [Haruki/UniveralFileFinder#1]
If new files get created or other files deleted the software does not recognize these changes, unless the software gets restarted.

Desired behaviour: 
  Every time the user looks for a specific file revalidate the directory contents.

**Comment by Haruki** [comment]
Hi [resTive2k12](https://github.com/resTive2k12)
this will be addressed soonish™

**Comment by Haruki** [comment]
Hi,
please check release 0.5
